### ISSUE TITLE
Updated readme

### ISSUE THREAD

**Issue by ijdickinson** [canmom/taasen#1]
Update the readme to be more informative. For example:

* add a link to the game itself
* outline the structure of the app
* some screenshots
* summarise  the gameplay

**Comment by canmom** [comment]
I've added some screenshots and a concise statement of the game rules. There is a placeholder link to where the game will be hosted online, which will be filled in shortly. I will add some description of the structure of the app.

**Comment by canmom** [comment]
I've now described the structure of the app in some detail, and (after some difficulties getting Vue to play nicely with Github Pages) deployed a live version of the game.
